name: inception

services:
  nginx:
    image: nginx_inception
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "4000:4000"
    volumes:
      - wordpress_data:/var/www/html
      - website_data:/var/www/static
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - docker-network

  wordpress:
    image: wordpress_inception
    container_name: wordpress
    build: ./requirements/wordpress
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    depends_on:
      - mariadb
    networks:
      - docker-network

  mariadb:
    image: mariadb_inception
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - docker-network

  adminer:
    image: adminer_inception
    container_name: adminer
    build: ./requirements/adminer
    restart: unless-stopped
    environment:
    - ADMINER_DESIGN=galkaev
    env_file:
      - .env
    networks:
      - docker-network

  static-site:
    image: alpine:3.23
    container_name: static_site
    networks:
      - docker-network
    depends_on:
      - mariadb
    volumes:
      - ./requirements/static_site/html:/src
      - website_data:/var/www/static
    command: sh -c "sleep 2 && cp -r /src/* /var/www/static/"

  redis:
    image: redis_inception
    container_name: redis
    build: ./requirements/redis
    restart: unless-stopped
    networks:
      - docker-network

  uptime-kuma:
    image: uptime_kuma_inception
    container_name: uptime_kuma
    build: ./requirements/uptime_kuma
    restart: unless-stopped
    volumes:
      - kuma_data:/app/data
    secrets:
      - kuma_password
    networks:
      - docker-network


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${USER_HOME}/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${USER_HOME}/data/wordpress

  website_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${USER_HOME}/data/website

  kuma_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${USER_HOME}/data/kuma


networks:
  docker-network:
    driver: bridge


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  kuma_password:
    file: ../secrets/kuma_password.txt
